### ISSUE TITLE
시간표 시작 시간 특정 불가

### ISSUE THREAD

**Issue by NamSangwon** [CSID-DGU/2023-1-OSSP2-HotSix-6#6]
에브리타임 시간표의 기본 시작 시간이 오전 9시입니다. 
따라서 오픈소스를 통해 시간표 이미지를 배열로 변환하면 오전 9시부터 [[0, 0, 0, 0, 0, 0, 0], [0, 1, 0, 0, 1, 0, 0], ...]와 같이 변환됩니다.

그런데 시간표에 오전 9시를 넘어서 오전 8시의 강의를 추가하게 되면 
오전 8시부터 [[0, 1, 0, 0, 1, 0, 0], [0, 1, 0, 0, 1, 0, 0], ...]와 같이 변환됩니다.

이렇게 되면 배열로 변환하였을 때 오전 8시에 시작하였는지 오전 9시에 시작하였는지 시작 시간을 특정할 수 없는 문제가 발생합니다.
이에 대한 문제를 해결 방법을 찾기 위해 이슈 등록합니다.

추가 참고 자료는 Notion의 [Project Table>시간표 등록 test 결과 및 시작 시간]에 올려놨으니 확인 부탁드립니다.

**Comment by bunju20** [comment]
일단 제 생각엔... 두가지 방법 정도가 있을것같은데 

**1. 사용자에게 시간을 입력받는 방법** 
= 가장 빠르게 시작하는 수업이 몇시인지를 받아오는건데. 드롭다운 형식으로 몇시 몇분에 수업이 시작하는지 추가하면 쉽게 해결할수 있을것같습니다. (프론트가 시간표 입력할때 같이 입력)

**2.OCR(Optical Character Recognition)을 이용해 이 텍스트를 추출하고 파싱해보기** 
= 글씨도 인식해서 받아오고 그걸로 처리하기. 

이정도 방법이 있을것 같습니다. 전자는 사용자가 실수하면 시간표가 틀리게 나올수도 있고 후자는 그런 경우는 없지만 너무 무거워진다는 단점이 있을것같아요. 혹시 어떤방법이 좋을것 같으신가요

**Comment by sillonjeu** [comment]
저는 1번 방안이 좀더 괜찮을거 같습니다. 케이스도 크게 많지 않을거 같네요

**Comment by bunju20** [comment]
넵 그러면 시간표입력 페이지에 해당부분 추가하겠습니다!
